# Demo Client for Passmeister Apple Wallet and Google Wallet API
#
# [www.passmeister.com](https://www.passmeister.com).
#
# OpenAPI spec version: 1.0.0
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git

#' @title Pass operations
#' @description swagger.Pass
#'
#' @field path Stores url path of the request.
#' @field apiClient Handles the client-server communication.
#' @field userAgent Set the user agent of the request.
#'
#' @importFrom R6 R6Class
#'
#' @section Methods:
#' \describe{
#'
#' create_or_update_pass This method creates or (if the pass id already exists) updates a pass, so you don&#39;t have to track ids and creation status of your passes.
#'
#'
#' delete_pass Delete pass by pass id.
#'
#'
#' get_pass Get pass information by pass id.
#'
#'
#' pass_list Retrieve the list of active pass ids for a given pass type.
#'
#'
#' pass_sync Send updates to all active passes for a given pass type.
#'
#' }
#'
#' @export
PassApi <- R6::R6Class(
  'PassApi',
  public = list(
    userAgent = "Swagger-Codegen/1.0.0/r",
    apiClient = NULL,
    initialize = function(apiClient){
      if (!missing(apiClient)) {
        self$apiClient <- apiClient
      }
      else {
        self$apiClient <- ApiClient$new()
      }
    },
    create_or_update_pass = function(pass_type_id, pass_id, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- character()

      if (!missing(`pass_type_id`)) {
        queryParams['passTypeId'] <- pass_type_id
      }

      if (!missing(`pass_id`)) {
        queryParams['passId'] <- pass_id
      }

      urlPath <- "/pass"
      resp <- self$apiClient$callApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "POST",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)
      
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        # void response, no need to return anything
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        Response$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        Response$new("API server error", resp)
      }

    },
    delete_pass = function(pass_type_id, pass_id, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- character()

      if (!missing(`pass_type_id`)) {
        queryParams['passTypeId'] <- pass_type_id
      }

      if (!missing(`pass_id`)) {
        queryParams['passId'] <- pass_id
      }

      urlPath <- "/pass"
      resp <- self$apiClient$callApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "DELETE",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)
      
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        # void response, no need to return anything
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        Response$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        Response$new("API server error", resp)
      }

    },
    get_pass = function(pass_type_id, pass_id, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- character()

      if (!missing(`pass_type_id`)) {
        queryParams['passTypeId'] <- pass_type_id
      }

      if (!missing(`pass_id`)) {
        queryParams['passId'] <- pass_id
      }

      urlPath <- "/pass"
      resp <- self$apiClient$callApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "GET",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)
      
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        # void response, no need to return anything
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        Response$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        Response$new("API server error", resp)
      }

    },
    pass_list = function(pass_type_id, page, limit, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- character()

      if (!missing(`pass_type_id`)) {
        queryParams['passTypeId'] <- pass_type_id
      }

      if (!missing(`page`)) {
        queryParams['page'] <- page
      }

      if (!missing(`limit`)) {
        queryParams['limit'] <- limit
      }

      urlPath <- "/pass/list"
      resp <- self$apiClient$callApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "GET",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)
      
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        # void response, no need to return anything
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        Response$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        Response$new("API server error", resp)
      }

    },
    pass_sync = function(pass_type_id, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- character()

      if (!missing(`pass_type_id`)) {
        queryParams['passTypeId'] <- pass_type_id
      }

      urlPath <- "/pass/sync"
      resp <- self$apiClient$callApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "POST",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)
      
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        # void response, no need to return anything
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        Response$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        Response$new("API server error", resp)
      }

    }
  )
)
